name: Update Downstream Templates
on:
  push:
    branches:
      - main

jobs:
  update-template:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Template A
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Clone SaaS-Template repository (Template B)
      run: |
        git clone https://Miyamura80:${{ secrets.GH_PAT }}@github.com/Miyamura80/SaaS-Template.git templateB

    - name: Copy all files to Template B
      run: |
        # First ensure we're copying to the correct location
        # Use --checksum to compare actual file contents instead of timestamps
        rsync -av --checksum --itemize-changes \
          --exclude='.git' \
          --exclude='.github/workflows/update_downstream.yaml' \
          ./ templateB \
          --remove-source-files

    - name: Clean up nested directories
      working-directory: templateB
      run: |
        # Check if nested templateB directory exists and move contents up if needed
        if [ -d "templateB" ]; then
          mv templateB/* .
          rm -rf templateB
        fi

    - name: Commit and push changes to SaaS-Template
      working-directory: templateB
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        # Stage all changes, including deletions
        git add -A
        # Only commit if there are actual changes
        git diff --staged --quiet || git commit -m "Update SaaS-Template from Python-Template"
        git push origin main
