name: Update Downstream Templates
on:
  push:
    branches:
      - main

jobs:
  update-template:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Template A
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Clone SaaS-Template repository (Template B)
      run: |
        git clone https://Miyamura80:${{ secrets.GH_PAT }}@github.com/Miyamura80/SaaS-Template.git templateB

    - name: Copy all files to Template B
      run: |
        # Create a temporary directory for the operation
        mkdir temp_dir
        
        # Copy all files to temp directory first, excluding .git and the workflow file
        cp -r $(ls -A | grep -v '.git\|.github') temp_dir/
        cp -r .github temp_dir/
        rm -f temp_dir/.github/workflows/update_downstream.yaml
        
        # Clean the target directory (except .git)
        find templateB -mindepth 1 -not -path 'templateB/.git*' -delete
        
        # Move files from temp to target
        cp -r temp_dir/* temp_dir/.* templateB/ 2>/dev/null || true
        
        # Cleanup
        rm -rf temp_dir

    - name: Commit and push changes to SaaS-Template
      working-directory: templateB
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add -A
        git diff --staged --quiet || git commit -m "Update SaaS-Template from Python-Template"
        git push origin main
