name: Update Downstream Templates
on:
  push:
    branches:
      - main

jobs:
  update-template:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Template A
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Clone SaaS-Template repository (Template B)
      run: |
        git clone https://Miyamura80:${{ secrets.GH_PAT }}@github.com/Miyamura80/SaaS-Template.git templateB

    - name: Copy files to Template B (preserving existing files)
      run: |
        # Copy files one category at a time, using cp -n to never overwrite existing files
        for item in $(ls -A | grep -v '.git\|.github\|templateB'); do
          if [ -e "templateB/$item" ]; then
            echo "Skipping existing item: $item"
          else
            cp -r "$item" templateB/
            echo "Copied new item: $item"
          fi
        done
        
        # Handle .github directory separately
        mkdir -p templateB/.github
        for item in .github/*; do
          if [ -e "templateB/$item" ]; then
            echo "Skipping existing item: $item"
          else
            cp -r "$item" "templateB/$item"
            echo "Copied new item: $item"
          fi
        done
        
        # Always exclude update_downstream.yaml
        rm -f templateB/.github/workflows/update_downstream.yaml

    - name: Commit and push changes to SaaS-Template
      working-directory: templateB
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add -A
        git diff --staged --quiet || git commit -m "Add new files from Python-Template"
        git push origin main
